from typing import Any


def greet(name: str, greeting: str = ...) -> str: ...

def connect(host, port: int = ..., timeout: float = ..., use_ssl: bool = ...): ...

async def fetch_data(url: str, headers: dict[str, str] | None = ...) -> bytes: ...

def search(query: str, /, *, limit: int = ..., offset: int = ...) -> list[Any]: ...

def log(message: str, *args: Any, level: str = ..., **kwargs: Any) -> None: ...

def concat(*parts: str) -> str: ...

def parse_config(path: str) -> dict[str, Any]: ...

def add(a, b): ...
