from enum import Enum, IntEnum, auto

from typing import Any


class Color(Enum):
    RED = ...
    GREEN = ...
    BLUE = ...

    def hex_code(self) -> str: ...

class HttpStatus(IntEnum):
    OK = ...
    NOT_FOUND = ...
    SERVER_ERROR = ...

    @classmethod
    def is_success(cls, code: int) -> bool: ...

class Permission(Enum):
    READ = ...
    WRITE = ...
    EXECUTE = ...

    def __str__(self) -> str: ...
